name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/dummy-source-repo
      - name: Sync files with dst-octocat-repsotiory!
        uses: denis-tingajkin/sync-files@main
        with:
          git-author-email: 'waroad@knu.ac.kr'
          git-author-name: 'waroad'
          src-repository: waroad/dummy-observer-repo
          allow-files-pattern: '.txt'
