name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: poll-github-repo/action@v1
        with:
          repo-to-sync: waroad/dummy-source-repo
          path-to-sync: data.txt
          cache-path: .last-sync
          tracking-issue-label: upstream-data-txt
          tracking-issue-title: "Update on {{ path }}: {{ sha-short }}"
          tracking-issue-body: |
            New commit in waroad/dummy-source-repo:

            **{{ message }}** [link]({{ url }})
          token: ${{ secrets.GITHUB_TOKEN }}
          yes-create-issues: false
